version: "3.8"
services: 
  database:
    build: ./database
    ports: 
      - 5432:5432
  
  backend:
    build: ./backend
    ports:
      - 8080:8080
    depends_on:
      - database
  
#  frontend:
#    build: ./frontend
#    ports:
#      - 8081:8080 
#
